 name: Sprint 

 on:
  push:
   branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:
    
 jobs:
   build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setuop-java@v2
        with:
          java-version: '17'

      - name: Unit Test
        run: mvn test
